services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      db.url: jdbc:mysql://mysql-container/assignment_submission_db
      db.username: root
      db.password: password123
    depends_on:
      - mysql-container
    
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - back-end

  
  mysql-container:
    image: mysql:8.2.0
    volumes:
       - dbdata:/var/lib/mysql
      
    environment:
      MYSQL_DATABASE: assignment_submission_db
      MYSQL_ROOT_PASSWORD: password123


volumes:
  dbdata: